name: Backend CD

on:
  push:
    branches:
      - main
    paths:
      - 'demo/**'

jobs:
  deploy:
    runs-on:  ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4