name: Backend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'demo/**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    #1.GithubからコードをDL
      - name: Check out repository
        uses: actions/checkout@v4
    #2.仮想環境（ubuntu^latest）にJavaをインストール
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
    #3.Mavenを用いてビルドとテストを実行
      - name: Build with Maven
        run:  |
          cd demo
          mvn clean test